### ISSUE TITLE
parse metadata from $metadata

### ISSUE THREAD

**Issue by skanikdale** [jaystack/odata-metadata#4]
I could see functions to extract info from schema in a JSON format. However, I could not see test / source code that would actually parse $metadata.  Is this still suported?

**Comment by lazarv** [comment]
Hello @skanikdale,
this library is using the JSON format parsed by the Olingo OData library and transforms it into typed classes to use in other libraries (JayData and odata-v4-server) and to be TypeScript ready. Like in jaydata-dynamic-metadata, here: https://github.com/jaystack/jaydata-dynamic-metadata/blob/master/src/metadataHandler.ts#L25
Use ```odatajs``` or our fork, ```jaydata-odatajs``` to parse the metadata XML and transform it into JSON format.

**Comment by skanikdale** [comment]
I could parse metaData with odatajs library. Thanks.
